== Probability Theory


Let $X$ be a *discrete random* variable with probability $p_X(x)$ of assuming the value $x$.

It will then have an *expected value* (mean) $mu=bb(E)(X)=sum_x x p_X(x)$

*Variance* $sigma^2=V(X)=bb(E)(X^2)-(bb(E)(X))^2=sum_x(x-bb(E)(X))^2p_X(x)$ where $sigma$ is the standard deviation.

If $X$ is instead continuous it will have a probability density function $f_X(x)$ and the sums above will instead be integrals with $p_X(x)$ replaced by $f_X(x)$.

Expectation is linear:
$bb(E)(a X+b Y) = a bb(E)(X)+b bb(E)(Y)$

For independent $X$ and $Y$, $V(a X+b Y) = a^2 V(X)+b^2 V(Y)$.

=== Discrete distributions

==== First success distribution
The number of trials needed to get the first success in independent yes/no experiments, each which yields success with probability $p$ is $upright("Fs")(p), 0 <= p <= 1$.
$p(k)=p(1-p)^{k-1},\,k=1,2, dots$
$mu = frac(1, p),\,sigma^2=frac(1-p, p^2)$

==== Poisson distribution
The number of events occurring in a fixed period of time $t$ if these events occur with a known average rate $kappa$ and independently of the time since the last event is $upright("Po")(lambda), lambda=t kappa$.
$p(k)=e^{-lambda}frac(lambda^k, k!), k=0,1,2, dots$
$mu=lambda,\,sigma^2=lambda$

=== Continuous distributions

==== Uniform distribution
If the probability density function is constant between $a$ and $b$ and 0 elsewhere it is $upright("U")(a,b), a<b$.
$f(x) = cases(
  frac(1, b-a) & a<x<b,
  0 & "otherwise"
)$
$mu=frac(a+b, 2),\,sigma^2=frac((b-a)^2, 12)$

==== Exponential distribution
The time between events in a Poisson process is $upright("Exp")(lambda), lambda>0$.
$f(x) = cases(
  lambda e^{-lambda x} & x >= 0,
  0 & x<0
)$
$mu=frac(1, lambda),\,sigma^2=frac(1, lambda^2)$

==== Normal distribution
Most real random values with mean $mu$ and variance $sigma^2$ are well described by $cal(N)(mu,sigma^2),\,sigma>0$.
$f(x) = frac(1, sqrt(2 pi sigma^2))e^{-frac((x-mu)^2, 2sigma^2)}$
If $X_1 ~ cal(N)(mu_1,sigma_1^2)$ and $X_2 ~ cal(N)(mu_2,sigma_2^2)$ then
$a X_1 + b X_2 + c ~ cal(N)(mu_1+mu_2+c,a^2 sigma_1^2+b^2 sigma_2^2)$

=== Markov chains
A _Markov chain_ is a discrete random process with the property that the next state depends only on the current state.
Let $X_1,X_2, dots$ be a sequence of random variables generated by the Markov process.
Then there is a transition matrix $bold(P) = (p_(i j))$, with $p_(i j) = Pr(X_n = i | X_(n-1) = j)$,
and $bold(p)^((n)) = bold(P)^n bold(p)^((0))$ is the probability distribution for $X_n$ (i.e., $p^((n))_i = Pr(X_n = i)$),
where $bold(p)^((0))$ is the initial distribution.

==== Stationary distribution
$bold(pi)$ is a stationary distribution if $bold(pi) = bold(pi P)$.
If the Markov chain is _irreducible_ (it is possible to get to any state from any state),
then $pi_i = frac(1, bb(E)(T_i))$ where $bb(E)(T_i)$ is the expected time between two visits in state $i$.
$pi_j / pi_i$ is the expected number of visits in state $j$ between two visits in state $i$.

For a connected, undirected and non-bipartite graph, where the transition probability is uniform among all neighbors, $pi_i$ is proportional to node $i$'s degree.

==== Ergodicity
A Markov chain is _ergodic_ if the asymptotic distribution is independent of the initial distribution.
A finite Markov chain is ergodic iff it is irreducible and _aperiodic_ (i.e., the gcd of cycle lengths is 1).
$lim_(k -> infinity) bold(P)^k = bold(1) pi$.

==== Absorption
A Markov chain is an A-chain if the states can be partitioned into two sets $bold(A)$ and $bold(G)$, such that all states in $bold(A)$ are absorbing ($p_(i i)=1$), and all states in $bold(G)$ leads to an absorbing state in $bold(A)$.
The probability for absorption in state $i in bold(A)$, when the initial state is $j$, is $a_(i j) = p_(i j)+sum_(k in bold(G)) a_(i k) p_(k j)$.
The expected time until absorption, when the initial state is $i$, is $t_i = 1+sum_(k in bold(G)) p_(k i) t_k$.


#include "monty_hall.typ"

#include "binomial_distribution.typ"
